
### SHOW ALL TRIPS
GET http://localhost:8000/api/trips/
Content-Type: application/json


### REGISTER A USER

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{ "username": "kat22",
  "email": "kat@email.com2",
  "profileImage": "image.jpg",
  "userCountry": "UK",
  "password": "pass",
  "passwordConfirmation": "pass"

}

### TRIP LIKE VIEW
POST http://localhost:8000/api/trips/24/like/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJleHAiOjE2MjQ4Njk4MTh9.al8FSKag25MQrT3zW-9mjRFQftEC1h5UJneD51df1Lk


http://localhost:3000/triplists/14

http://localhost:3000/home/triplists/14